'use client';
import Link from 'next/link';
import {useLanguage,LanguageSwitch} from '@/components/LanguageProvider';

const navigation = [{slug:"terms",zh:"服务条款",en:"Terms"},{slug:"privacy",zh:"隐私政策",en:"Privacy"},{slug:"guidelines",zh:"社区规范",en:"Guidelines"}];
const sections = [
  {id:"section-1", zhTitle:"关于星流", enTitle:"About Starflow", zh:["星流 Starflow 是由 WEIZAI 品牌提供的独立社交平台，面向包括中国大陆在内的全球用户。服务涵盖公开个人资料、动态发布、互动及实际开放的相关功能。", "本条款适用于您访问、注册和使用星流网站。网站上介绍的未来功能不代表目前均已提供；具体功能以实际页面和正式公告为准。"], en:["Starflow is an independent social platform presented under the WEIZAI brand for users worldwide, including mainland China. The service includes public profiles, posts, interactions and other features actually made available.", "These Terms apply when you access, register for or use Starflow. Descriptions of possible future features do not mean they are currently offered; availability is determined by the live service and published announcements."]},
  {id:"section-2", zhTitle:"接受条款与附属规则", enTitle:"Acceptance and related policies", zh:["访问或注册服务即表示您已阅读本条款；依法需要单独同意的个人信息处理，不因接受本条款而自动视为同意。隐私政策说明数据处理，社区规范说明内容与行为底线。", "如您不同意本条款，请不要创建账号或继续使用本服务。依法需要特定方式同意或通知的事项，将依适用法律另行处理。"], en:["By accessing or registering for the service, you acknowledge these Terms. Agreement to Terms is not a substitute for separate consent where data-protection law requires one. The Privacy Policy describes data processing and the Community Guidelines describe behavioral standards.", "Do not use the service if you do not agree. Additional notices and consent will be provided where required by law."]},
  {id:"section-3", zhTitle:"使用年龄", enTitle:"Age eligibility", zh:["星流的用户年龄要求为年满 18 周岁。未满 18 周岁者不得注册或使用账号功能。", "星流目前不以未成年人为目标用户；针对年龄不符的账号，我们可能在核实后采取限制措施。年龄保障措施会根据适用法律和服务实际情况完善。"], en:["Starflow is intended for users aged 18 or older. Persons under 18 must not register or use account features.", "Starflow does not target minors. Accounts found not to meet the age requirement may be restricted after appropriate review. Age safeguards will be developed in line with applicable laws and available technology."]},
  {id:"section-4", zhTitle:"注册、验证与账号安全", enTitle:"Accounts, verification and security", zh:["您应提供真实、合法可使用的注册信息，保护密码、验证邮件和设备，并及时报告疑似盗号。不得冒用他人身份、出售或非法获取账号。", "邮箱找回等功能以实际部署的身份验证流程为准；仅知晓用户 ID 不构成账号所有权证明。平台不会向您索取第三方账号的原始密码。"], en:["Provide valid registration information, protect credentials and devices, and promptly report suspected account compromise. Impersonation, illicit account trading and unauthorized access are prohibited.", "Recovery methods depend on the authentication flows actually deployed. Knowledge of an account ID alone does not prove ownership. Starflow will not ask for passwords to third-party accounts."]},
  {id:"section-5", zhTitle:"社区行为与内容规范", enTitle:"Conduct and community rules", zh:["禁止违法内容、骚扰威胁、仇恨攻击、儿童性剥削内容、非自愿私密影像、诈骗、恶意软件、侵犯隐私、冒名顶替以及侵犯他人权利的内容。", "具体规则、举报条件和执行原则见《社区规范》。我们会根据适用法律和安全风险决定何时限制可见性、删除内容或暂停账号；当前自动与人工审核能力仍在建设。"], en:["Illegal content, harassment, threats, hateful conduct, child sexual exploitation material, non-consensual intimate imagery, fraud, malware, privacy violations, impersonation and infringement are prohibited.", "See the Community Guidelines for definitions, reporting and enforcement principles. Content or accounts may be restricted in response to law or safety risks; automated and human review capabilities are still being developed."]},
  {id:"section-6", zhTitle:"您发布内容的权利", enTitle:"Your content and license", zh:["在法律允许的范围内，您保留对原创内容的相应权利，并保证有权上传、公开和授权所发布内容。", "为运营、展示、传输、储存、调整格式、备份和维护安全，您给予星流一项非独占、全球范围、免许可费、仅限提供服务所需的使用许可，并允许必要的服务供应商在同一范围内处理内容。除法律或既有合法备份义务外，删除内容后该许可就相关内容终止。", "其他用户可能在内容公开期间访问、截图或分享您的内容；平台无法保证已被第三方保存的副本同步删除。"], en:["You retain applicable ownership of your original content and represent that you have the rights needed to upload and share it.", "Solely to operate, display, transmit, store, format, back up and secure the service, you grant Starflow a non-exclusive, worldwide, royalty-free license, including necessary processing by service providers. This license ends for removed content, except where lawful backups or obligations require limited retention.", "Others may view, capture or redistribute publicly available posts; Starflow cannot guarantee removal of copies independently kept by third parties."]},
  {id:"section-7", zhTitle:"知识产权与版权", enTitle:"Intellectual property and copyright", zh:["请勿在缺乏合法权限的情况下上传受版权、商标或其他权利保护的资料。您可就涉嫌侵权内容使用网站实际开放的举报入口提交链接、权属信息和相关证据。", "我们依据适用法律处理有效的侵权通知与争议，可能采取限制访问或移除内容等措施；反通知和申诉程序以实际开放的渠道为准。"], en:["Do not upload works, trademarks or other protected material without lawful permission. You may use reporting features actually available on the website to flag suspected infringement, supplying links, ownership details and supporting information.", "We assess valid infringement notifications and disputes under applicable law and may restrict or remove content. Counter-notice and appeal methods depend on the channels actually made available."]},
  {id:"section-8", zhTitle:"举报与平台处置", enTitle:"Reports and platform enforcement", zh:["网站当前为用户提供基本的动态举报入口。请如实提交涉嫌违法或违反社区规范的内容及相关信息。提交举报不保证即时处理或特定结论。", "根据违法风险和严重程度，星流可能在具备相应处理能力时移除内容、限制功能或账号；依法需要告知理由或提供救济时，我们将遵守适用程序。"], en:["The website currently provides a basic reporting feature for posts. Please accurately describe suspected unlawful content or breaches of the Community Guidelines. Submitting a report does not guarantee immediate handling or a particular result.", "Depending on legal risk and seriousness, Starflow may remove content or restrict features or accounts where its enforcement capability allows. Legally required notices, reasons and remedies will be respected."]},
  {id:"section-9", zhTitle:"服务变更与账号终止", enTitle:"Service changes and account closure", zh:["出于维护、安全、法律义务或产品调整，我们可能变更、暂停或终止功能，并在法律要求时通知用户。", "您可以随时停止使用服务。账号注销、完整数据导出和自助删除入口尚未上线；关于个人信息的法定权利请参阅《隐私政策》。"], en:["Features may change, pause or end for maintenance, security, legal or product reasons. We will provide notice where law requires it.", "You can stop using the service at any time. Self-service account closure, comprehensive data export and deletion features are not yet available; please see the Privacy Policy for applicable data rights."]},
  {id:"section-10", zhTitle:"外部服务与链接", enTitle:"Third-party services and links", zh:["星流可能依赖 Supabase、Cloudflare，以及启用后用于授权登录和发送邮件的第三方服务。第三方服务可能有独立条款与隐私说明。", "未经实际配置或授权的 Google 登录、邮件等选项不应视为已可用；平台不保证第三方网站、产品或内容的持续可用。"], en:["Starflow may use Supabase, Cloudflare and, if configured, third-party sign-in or email providers. They may publish separate terms and privacy notices.", "Unconfigured sign-in or messaging options are not operational. Starflow does not guarantee availability of external websites or services."]},
  {id:"section-11", zhTitle:"平台安全", enTitle:"Platform security", zh:["不得使用撞库、恶意脚本、未经授权的抓取、攻击流量、绕过安全措施或其他手段破坏服务安全与正常运行。", "如发现安全问题，请勿公开真实用户凭据或个人信息，也不得利用漏洞访问非本人数据。"], en:["Credential stuffing, malicious automation, unauthorized scraping, attack traffic, bypassing security safeguards and other interference are prohibited.", "If you discover a security issue, do not disclose real user credentials or personal data, or exploit vulnerabilities to access information belonging to others."]},
  {id:"section-12", zhTitle:"责任与法定保障", enTitle:"Responsibility and mandatory safeguards", zh:["星流会采取合理措施维护服务运行，但互联网服务可能因维护、故障或第三方服务原因出现中断。我们不会保证服务绝不中断。", "本条款中的任何说明均不排除法律禁止排除的责任，也不限制您依据适用法律享有的消费者与个人信息保护权利。"], en:["Starflow takes reasonable steps to maintain the service, but maintenance, failures and third-party services may cause interruptions. Uninterrupted operation is not guaranteed.", "Nothing in these Terms excludes liability that cannot lawfully be excluded or limits mandatory consumer and data-protection rights."]},
  {id:"section-13", zhTitle:"争议及地区法律", enTitle:"Disputes and regional laws", zh:["发生争议时，建议先利用网站实际提供的申诉或举报方式沟通；涉及法定权利时，您仍可依法寻求监管部门、法院或其他法定救济。", "星流服务面向全球，但各地区法律可能不同；本条款不剥夺任何司法辖区用户依法享有的不可放弃的权利。"], en:["If a dispute arises, you may first use applicable reporting or appeal channels actually available on the site. Legal rights to seek regulatory, judicial or other remedies remain unaffected.", "Starflow serves a global audience, but legal requirements vary by region. These Terms do not waive non-excludable rights provided by applicable law."]},
  {id:"section-14", zhTitle:"规则更新与语言", enTitle:"Updates and languages", zh:["我们可能根据功能、安全要求和法律变化更新条款。涉及重要权利义务的更改，将依适用法律以适当方式告知用户。", "本条款提供中文与英文版本。如翻译存在差异，不影响您根据适用法律享有的强制性权利。"], en:["We may update these Terms to reflect changes in features, security needs and law. Material changes affecting rights or obligations will be communicated as required by applicable law.", "These Terms are available in Chinese and English. Translation differences do not affect mandatory rights under applicable law."]},
  {id:"section-15", zhTitle:"品牌与关联政策", enTitle:"Brand and related policies", zh:["服务品牌：星流 Starflow · WEIZAI。请同时阅读《隐私政策》和《社区规范》，了解个人信息处理方式与内容发布规则。", "本版更新日期：2026 年 10 月 9 日。网站内容或功能如有变化，适用页面会相应更新。"], en:["Service brand: Starflow · WEIZAI. Please also read the Privacy Policy and Community Guidelines for information about data handling and content rules.", "Last updated: 9 October 2026. Policy pages may be revised when the service or its features change."]},
];
export default function LegalPage(){
  const {lang}=useLanguage();
  const en=lang==='en';
  return <main className="document sf-legal-page" style={{maxWidth:920, color:'#192c31'}}>
    <div className="sf-legal-top" style={{marginBottom:20}}><Link href="/">← 星流 Starflow</Link><LanguageSwitch/></div>
    <nav aria-label={en?'Legal documents':'法律文件'} style={{display:'flex',flexWrap:'wrap',gap:10,margin:'20px 0 35px'}}>
      {navigation.map(item=><Link key={item.slug} href={'/'+item.slug} aria-current={item.slug==="terms"?'page':undefined} style={{padding:'9px 14px',borderRadius:999,border:'1px solid #dce4e4',background:item.slug==="terms"?'#e6f4f1':'white',fontSize:13}}>{en?item.en:item.zh}</Link>)}
    </nav>
    <p style={{fontSize:12,letterSpacing:'.08em',color:'#657279',marginBottom:10}}>{en?'STARFLOW · POLICY CENTER':'星流 STARFLOW · 政策中心'}</p>
    <h1>{en?"Terms of Service":"服务条款"}</h1>
    <p style={{fontSize:16,lineHeight:1.9}}>{en?"These Terms govern the use of Starflow, an independent social service under the WEIZAI brand.":"本条款适用于您使用 WEIZAI 品牌旗下的独立社交服务——星流 Starflow。"}</p>
    <nav aria-label={en?'Contents':'目录'} style={{padding:'18px 20px',background:'#f1f6f5',borderRadius:14,marginBottom:32}}>
      <strong>{en?'Contents':'目录'}</strong>
      <ol style={{columns:'2 220px',columnGap:30,paddingLeft:22,fontSize:13,lineHeight:2}}>
        {sections.map(s=><li key={s.id} style={{breakInside:'avoid'}}><a href={'#'+s.id}>{en?s.enTitle:s.zhTitle}</a></li>)}
      </ol>
    </nav>
    <article>{sections.map((s,i)=><section id={s.id} key={s.id} style={{scrollMarginTop:20,borderBottom:'1px solid #e4ebea',padding:'8px 0 18px'}}>
      <h2 style={{fontSize:21,lineHeight:1.45,margin:'16px 0'}}>{String(i+1).padStart(2,'0')}. {en?s.enTitle:s.zhTitle}</h2>
      {(en?s.en:s.zh).map((p,j)=><p key={j} style={{lineHeight:1.95,margin:'12px 0',overflowWrap:'anywhere'}}>{p}</p>)}
    </section>)}</article>
    <footer style={{padding:'35px 0',fontSize:13,color:'#67757b'}}>
      <p>{en?'Related policies':'相关政策'}：{navigation.filter(n=>n.slug!=="terms").map((n,i)=><span key={n.slug}>{i>0?' · ':''}<Link href={'/'+n.slug}>{en?n.en:n.zh}</Link></span>)}</p>
      <p>© 2026 Starflow · WEIZAI</p>
    </footer>
  </main>;
}
