'use client';
import Link from 'next/link';
import {useLanguage,LanguageSwitch} from '@/components/LanguageProvider';

const navigation = [{slug:"terms",zh:"服务条款",en:"Terms"},{slug:"privacy",zh:"隐私政策",en:"Privacy"},{slug:"guidelines",zh:"社区规范",en:"Guidelines"}];
const sections = [
  {id:"section-1", zhTitle:"适用范围与价值", enTitle:"Scope and values", zh:["本社区规范适用于星流 Starflow（WEIZAI 品牌）的账号、动态、回复、个人资料以及实际提供的其他互动功能。星流面向包括中国大陆在内的全球用户。", "我们鼓励真实表达与尊重不同观点，同时反对骚扰、欺诈、侵犯隐私以及对他人构成危险的行为。判断违规时，应考虑内容、语境、风险与适用法律。"], en:["These Community Guidelines apply to accounts, posts, replies, profiles and other active Starflow features under the WEIZAI brand. The service is intended for users worldwide, including mainland China.", "We support authentic expression and respectful disagreement while opposing harassment, fraud, privacy violations and conduct that endangers others. Context, risk and applicable law matter when assessing potential breaches."]},
  {id:"section-2", zhTitle:"骚扰、霸凌与歧视", enTitle:"Harassment, bullying and hateful conduct", zh:["不得以辱骂、持续跟踪、煽动围攻、恶意曝光、威胁或羞辱方式针对他人。不得依据种族、民族、宗教、性别、性取向、残障等受保护特征煽动仇恨、暴力或排斥。", "合理的公共议题批评不自动构成骚扰；处理时应关注上下文、目标对象、重复性和潜在伤害。"], en:["Do not target others with repeated abuse, stalking, dogpiling, doxxing, threats or humiliation. Hate, dehumanization or incitement based on protected characteristics is prohibited.", "Good-faith criticism of public issues is not automatically harassment; context, targeting, repetition and risk matter."]},
  {id:"section-3", zhTitle:"威胁、暴力与危险行为", enTitle:"Threats, violence and dangerous acts", zh:["禁止可信的人身伤害威胁、煽动暴力、组织暴力活动或传播旨在指导实施严重伤害的内容。", "新闻、教育或公益讨论应关注语境；如对公众安全有迫切风险，平台应建立紧急升级及依法报告程序。"], en:["Credible threats, incitement to violence, organizing violence and instructions intended to facilitate serious harm are prohibited.", "News, education and public-interest context matter. Urgent safety risks require an escalation and lawful reporting process."]},
  {id:"section-4", zhTitle:"未成年人安全", enTitle:"Safety of children and young people", zh:["严格禁止儿童性剥削及虐待影像、诱骗未成年人进行性互动、性勒索、传播未成年人私密信息以及其他利用未成年人的行为。", "星流拟在初期只面向 18 岁以上用户；年龄核验和举报处置机制落地前，不应向未成年人开放。涉及儿童即时危险的情况应优先求助当地紧急服务并依法处置。"], en:["Child sexual abuse material, grooming, sexual extortion, disclosure of children’s intimate information and all sexual exploitation of minors are strictly prohibited.", "The initial proposed service is 18+. Minors must not be admitted before age and safety systems are in place. Imminent danger should be reported to local emergency services and handled lawfully."]},
  {id:"section-5", zhTitle:"性剥削及非自愿私密内容", enTitle:"Sexual exploitation and non-consensual intimate content", zh:["禁止未经同意发布或威胁发布私密影像、偷拍内容、性勒索、交易人口或强迫性行为相关内容。", "涉及成人敏感内容时应遵守当地法律和平台年龄政策；当前未建立年龄分级及敏感内容过滤，相关高风险内容应限制。"], en:["Non-consensual intimate imagery, threats to share it, voyeurism, sexual extortion, trafficking and coerced sexual material are prohibited.", "Adult-sensitive content must comply with local law and age policy. Until age-based controls and filters are implemented, high-risk sexual material should be restricted."]},
  {id:"section-6", zhTitle:"自伤、自杀与饮食障碍", enTitle:"Self-harm, suicide and eating disorders", zh:["不得鼓励、指导、挑战或美化自杀、自伤及危险性饮食障碍行为，也不得针对处于危机中的人实施骚扰。", "允许支持性、求助性和康复交流；如有人面临迫切危险，应联系当地紧急服务或可信赖的现实支持。"], en:["Do not promote, instruct, challenge or glorify suicide, self-harm or dangerous eating-disorder behaviors, or harass people in crisis.", "Support-seeking, recovery and educational conversations may be allowed. In immediate danger, contact local emergency services or trusted offline support."]},
  {id:"section-7", zhTitle:"隐私、个人信息与冒名顶替", enTitle:"Privacy, personal information and impersonation", zh:["不得在未经合法授权的情况下公开他人的住址、电话、证件、私人联系方式、定位或其他可能带来风险的非公开信息。", "不得冒充个人、品牌、机构或官方账号误导用户。评论、戏仿等合理表达需清晰标注且不得构成欺诈。"], en:["Do not disclose non-public addresses, phone numbers, identity documents, contact details, precise location or other risky private information without lawful authorization.", "Do not deceptively impersonate people, brands, organizations or official accounts. Commentary and parody must be clearly distinguishable and must not be fraudulent."]},
  {id:"section-8", zhTitle:"欺诈、恶意软件和非法交易", enTitle:"Scams, malware and illicit trade", zh:["禁止钓鱼链接、金融诈骗、虚假投资承诺、账号盗用、恶意软件、窃取凭证及违法商品或服务交易。", "任何涉及支付、抽奖、推广或商业合作的功能在上线前均应另行制定规则和风险措施；当前星流没有因此自动授权交易活动。"], en:["Phishing, financial scams, false investment guarantees, account theft, malware, credential harvesting and trade in illegal goods or services are prohibited.", "Payments, contests, promotions or commercial partnerships require additional rules and safeguards before implementation; these Guidelines do not authorize such activities."]},
  {id:"section-9", zhTitle:"错误信息与冒充权威", enTitle:"Misleading content and false authority", zh:["禁止为实施诈骗、操纵他人或制造现实伤害而故意传播伪造的紧急通告、身份材料、危险健康建议等内容。", "意见、讽刺、艺术表达及善意错误不应仅因有争议而被自动移除；应考虑可核验事实、传播风险及当地法律。"], en:["Deliberately fabricated emergency alerts, identities, dangerous health claims or other deception intended to defraud or cause real-world harm are prohibited.", "Opinion, satire, art and good-faith errors should not be removed merely because they are controversial; evidence, harm and local law matter."]},
  {id:"section-10", zhTitle:"垃圾信息与自动化滥用", enTitle:"Spam and automated abuse", zh:["禁止机器批量刷屏、恶意营销、假互动、虚假粉丝、撞库登录、机器人滥发请求及绕过平台限制的行为。", "合理自动化、研究使用及辅助技术应以明确授权、限速和不侵犯他人权益为前提。"], en:["Mass posting, unsolicited spam, fake engagement, purchased followers, credential stuffing, bot flooding and evasion of safeguards are prohibited.", "Legitimate automation, research and accessibility tools require authorization, rate limits and respect for others’ rights."]},
  {id:"section-11", zhTitle:"著作权与内容来源", enTitle:"Copyright and attribution", zh:["上传作品前，应确认您具有相应权利或合法授权。不得盗用他人作品、冒充原创作者或伪造内容来源。", "如发现涉嫌侵权的动态，可通过当前可用的举报入口提供内容链接、权属依据和事实说明。"], en:["Before uploading a work, ensure you own it or have a lawful license. Unauthorized copying, false authorship and fabricated attribution are prohibited.", "You may report suspected infringing posts through an available reporting feature, providing the content link, relevant rights information and context."]},
  {id:"section-12", zhTitle:"举报与证据", enTitle:"Reports and evidence", zh:["现有网站支持对动态提交基本举报。请尽量提供违规内容的链接、发生经过和必要证据，避免再次公开他人的敏感信息。", "举报可能需要核实，提交举报不代表所举报内容必然违规，也不保证即刻处理。恶意重复举报或故意虚构事实同样可能违规。"], en:["The current site supports basic post reports. Include links, relevant facts and necessary evidence where possible, without re-publishing sensitive personal information.", "Reports may require review; a submission does not prove a violation or guarantee immediate action. Deliberately false or malicious mass reports may themselves violate these Guidelines."]},
  {id:"section-13", zhTitle:"处置方式与原则", enTitle:"Enforcement and proportionality", zh:["星流可能依法并结合事件严重程度，对违规内容或账号采取警告、限制展示、内容移除、功能限制、暂停或终止等适当措施。", "处理将考虑上下文、违规程度、重复性以及潜在误判。当前网站不提供全天候人工审核或固定处理时限的保证。"], en:["Depending on applicable law and seriousness, Starflow may use appropriate measures such as warnings, visibility restrictions, removal, feature limits, suspension or termination.", "Decisions should consider context, severity, repetition and the risk of mistakes. The site does not guarantee around-the-clock human review or a fixed handling time."]},
  {id:"section-14", zhTitle:"通知与申诉", enTitle:"Notices and appeals", zh:["如内容或账号受到影响，依法需要通知的决定将依据适用规则说明理由并提供相应的法定救济。", "目前网站主要提供动态举报记录，尚未开通完整的账号申诉和人工复核系统。请勿因他人善意举报或主张法定权利而骚扰、报复。"], en:["Where law requires notice of content or account decisions, reasons and legally required remedies will be handled under the applicable rules.", "The site currently focuses on recording post reports and does not yet provide a complete account appeal or human reconsideration system. Harassment or retaliation against good-faith reporters or people exercising lawful rights is prohibited."]},
  {id:"section-15", zhTitle:"地区要求与更新", enTitle:"Regional requirements and updates", zh:["星流面向全球用户，可能因不同地区的法律、安全要求或产品调整适用相应的使用限制。", "服务品牌：星流 Starflow · WEIZAI。本版更新日期：2026 年 10 月 9 日。相关政策和社区管理方式会随实际服务及法律变化调整。"], en:["Starflow serves a global audience. Region-specific restrictions may apply based on local law, safety requirements or service changes.", "Service brand: Starflow · WEIZAI. Last updated: 9 October 2026. Community policies and enforcement will evolve with the service and applicable laws."]},
];
export default function LegalPage(){
  const {lang}=useLanguage();
  const en=lang==='en';
  return <main className="document sf-legal-page" style={{maxWidth:920, color:'#192c31'}}>
    <div className="sf-legal-top" style={{marginBottom:20}}><Link href="/">← 星流 Starflow</Link><LanguageSwitch/></div>
    <nav aria-label={en?'Legal documents':'法律文件'} style={{display:'flex',flexWrap:'wrap',gap:10,margin:'20px 0 35px'}}>
      {navigation.map(item=><Link key={item.slug} href={'/'+item.slug} aria-current={item.slug==="guidelines"?'page':undefined} style={{padding:'9px 14px',borderRadius:999,border:'1px solid #dce4e4',background:item.slug==="guidelines"?'#e6f4f1':'white',fontSize:13}}>{en?item.en:item.zh}</Link>)}
    </nav>
    <p style={{fontSize:12,letterSpacing:'.08em',color:'#657279',marginBottom:10}}>{en?'STARFLOW · POLICY CENTER':'星流 STARFLOW · 政策中心'}</p>
    <h1>{en?"Community Guidelines":"社区规范"}</h1>
    <p style={{fontSize:16,lineHeight:1.9}}>{en?"Starflow aims to support authentic expression, respectful participation and personal safety. These rules apply to posts, replies, avatars, bios, handles and all platform conduct.":"我们希望星流是一个鼓励真实交流、尊重他人和保护人身安全的社区。以下规则适用于动态、评论、头像、简介、用户名以及其他用户行为。"}</p>
    <nav aria-label={en?'Contents':'目录'} style={{padding:'18px 20px',background:'#f1f6f5',borderRadius:14,marginBottom:32}}>
      <strong>{en?'Contents':'目录'}</strong>
      <ol style={{columns:'2 220px',columnGap:30,paddingLeft:22,fontSize:13,lineHeight:2}}>
        {sections.map(s=><li key={s.id} style={{breakInside:'avoid'}}><a href={'#'+s.id}>{en?s.enTitle:s.zhTitle}</a></li>)}
      </ol>
    </nav>
    <article>{sections.map((s,i)=><section id={s.id} key={s.id} style={{scrollMarginTop:20,borderBottom:'1px solid #e4ebea',padding:'8px 0 18px'}}>
      <h2 style={{fontSize:21,lineHeight:1.45,margin:'16px 0'}}>{String(i+1).padStart(2,'0')}. {en?s.enTitle:s.zhTitle}</h2>
      {(en?s.en:s.zh).map((p,j)=><p key={j} style={{lineHeight:1.95,margin:'12px 0',overflowWrap:'anywhere'}}>{p}</p>)}
    </section>)}</article>
    <footer style={{padding:'35px 0',fontSize:13,color:'#67757b'}}>
      <p>{en?'Related policies':'相关政策'}：{navigation.filter(n=>n.slug!=="guidelines").map((n,i)=><span key={n.slug}>{i>0?' · ':''}<Link href={'/'+n.slug}>{en?n.en:n.zh}</Link></span>)}</p>
      <p>© 2026 Starflow · WEIZAI</p>
    </footer>
  </main>;
}
