'use client';
import Link from 'next/link';
import {useLanguage,LanguageSwitch} from '@/components/LanguageProvider';

const navigation = [{slug:"terms",zh:"服务条款",en:"Terms"},{slug:"privacy",zh:"隐私政策",en:"Privacy"},{slug:"guidelines",zh:"社区规范",en:"Guidelines"}];
const sections = [
  {id:"section-1", zhTitle:"关于本政策", enTitle:"About this Policy", zh:["本政策介绍星流 Starflow（WEIZAI 品牌）如何在提供社交服务时处理个人信息，适用于包括中国大陆在内的全球用户。", "我们尊重用户依法享有的知情、访问、更正、删除等权利。星流目前只提供部分自助管理工具；对于法律要求的其他受理方式，需要结合实际服务能力与适用法律落实。"], en:["This Policy describes how Starflow, under the WEIZAI brand, handles personal data in connection with its social service for users worldwide, including mainland China.", "We respect applicable rights to information, access, correction and deletion. Only some self-service account management tools are currently available; additional lawful request handling depends on the applicable requirements and operational processes."]},
  {id:"section-2", zhTitle:"我们收集哪些信息", enTitle:"Categories of information collected", zh:["账号信息：邮箱、Supabase 身份标识、验证状态、经身份服务处理的登录凭据与会话；星流不应储存明文密码。", "您主动提供的信息：昵称、用户名或账号 ID、头像、个人简介、动态文字与图片、回复及提交的举报内容。", "社交互动：关注、点赞、书签、通知和时间信息。技术与安全信息可能包括设备或浏览器特征、IP 地址、时间戳、故障与防滥用日志，具体以 Cloudflare、Supabase 实际产生的记录为准。", "如果以后启用 Google 登录，可能接收获授权的基本账号资料；目前界面上标注“待配置”的入口不代表已经收集相关数据。"], en:["Account data includes email, Supabase authentication identifiers, verification status, credentials and sessions processed by the authentication service. Starflow should not store plaintext passwords.", "Information you provide includes display name, handle/account ID, avatar, biography, text and image posts, replies and submitted reports.", "Social interactions include follows, likes, bookmarks, notifications and timestamps. Technical/security information may include browser/device attributes, IP addresses, timestamps and anti-abuse logs as actually processed by Cloudflare and Supabase.", "If Google sign-in is later enabled, basic authorized profile data may be received. A “not configured” button does not mean such data is currently collected."]},
  {id:"section-3", zhTitle:"信息的来源", enTitle:"Sources of information", zh:["信息来自您输入与发布的内容、网站使用过程、身份验证及安全日志，或在您主动授权时来自第三方登录服务。", "其他用户的帖子、标签或举报可能包含关于您的信息；这不意味着我们会确认相关陈述属实。"], en:["Information comes from your inputs and posts, service use, authentication and security logs, and any third-party login you deliberately authorize.", "Other people’s posts or reports may include information about you. We do not assume the claims in those reports are accurate."]},
  {id:"section-4", zhTitle:"使用目的与处理依据", enTitle:"Purposes and legal bases", zh:["为创建和维护账号、执行验证、发布与展示内容、提供互动、保存账号偏好、处理用户请求和保障安全，我们处理必要数据；具体依据可能是履行服务合同、履行法律义务或依法适用的正当利益。", "对于可选邮件营销、非必要追踪、敏感个人信息或适用法律要求单独同意的处理活动，应在实际启用前提供独立选项并记录有效同意；同意可依法律撤回。", "面向中国大陆处理个人信息时，应依《个人信息保护法》确认相应合法性基础，不能把 GDPR 的“正当利益”直接当作中国法下的通用处理依据。"], en:["We process data as needed for accounts, authentication, posts and interactions, preferences, support and security, relying as applicable on performance of a contract, legal obligations or legitimate interests under laws that recognize that basis.", "Optional marketing, non-essential tracking, sensitive data and processing requiring separate consent must not start without suitable notices, valid choices and recorded consent. Consent may be withdrawn as the law allows.", "For mainland-China processing, an applicable lawful basis under the Personal Information Protection Law must be identified; GDPR legitimate interests must not be assumed to be a general PIPL basis."]},
  {id:"section-5", zhTitle:"哪些内容会公开", enTitle:"Public and non-public data", zh:["公开个人资料、头像、简介、已发布动态及互动可能被全球访问、引用、搜索或截图。请勿在公开内容中上传密码、身份证件、家庭地址或他人的隐私信息。", "账号邮箱和身份验证令牌不应以公开资料字段展示；具体访问权限依赖已部署的数据库 RLS 与安全配置，发布前必须实测验证。"], en:["Public profiles, avatars, biographies, posts and interactions may be viewed, shared, indexed or captured globally. Avoid posting passwords, IDs, home addresses or anyone else’s private information.", "Email addresses and authentication tokens should not be exposed as public profile fields. Actual restrictions depend on deployed database RLS and security configuration, which require pre-launch testing."]},
  {id:"section-6", zhTitle:"内容排序与自动决策", enTitle:"Feed ordering and automated decisions", zh:["当前基础应用采用时间顺序和关注关系等方式查询内容，不应将其描述为已经启用复杂的广告画像或算法推荐。", "如未来上线个性化推荐、自动内容处罚或对个人产生重大影响的自动化决策，需要补充说明处理逻辑、权利保护与适用的选择机制。"], en:["The current starter app uses time order and follows to retrieve content; it should not be described as operating advanced ad profiling or recommendation systems.", "If personalized recommendations, automated moderation or decisions with significant effects are introduced, this policy and the applicable safeguards must be updated first."]},
  {id:"section-7", zhTitle:"服务提供商与数据共享", enTitle:"Service providers and disclosure", zh:["网站基础设施与网络防护使用 Cloudflare，账号身份认证与数据库使用 Supabase；这些供应商可能为提供服务而处理必要的技术与账号数据。", "如果启用 Google 授权登录或第三方邮件服务，相关数据还可能依授权范围及服务目的与对应供应商交换。我们不会将向公众展示的内容误称为私人内容。", "遇到合法有效的司法或监管要求，我们会依据适用法律评估和处理；不会仅因本政策而出售个人信息。"], en:["Cloudflare supports hosting and network security, while Supabase provides authentication and database services. These suppliers may process technical and account information necessary to deliver their functions.", "If Google sign-in or third-party email delivery is enabled, relevant information may be shared with those providers according to the authorization and service purpose. Content displayed publicly is not private.", "We evaluate valid legal requests from authorities under applicable law. This Policy does not authorize the sale of personal information."]},
  {id:"section-8", zhTitle:"全球服务与跨境数据", enTitle:"Global service and cross-border data", zh:["星流所使用的 Supabase 项目目前部署于新加坡区域。Cloudflare 的全球网络、认证、日志及其他已启用服务可能在不同国家或地区处理数据。", "跨境数据处理应遵守适用的中国《个人信息保护法》、欧盟 GDPR、新加坡 PDPA 等相关规则，包括依法需要的告知、单独同意和数据传输保障。不同地区可能适用不同要求。", "请勿将数据托管地区与您的居住地区视为必然相同。公开动态可能被世界各地的其他用户访问。"], en:["The current Supabase project is deployed in Singapore. Cloudflare’s global network, authentication, logs and other enabled services may process information in more than one country or region.", "International processing must comply with applicable rules, including China’s PIPL, the EU GDPR and Singapore’s PDPA where relevant, such as required notice, separate consent and transfer safeguards. Local requirements differ.", "Data hosting location may differ from where you live. Public posts may be accessed by users around the world."]},
  {id:"section-9", zhTitle:"未成年人保护", enTitle:"Children and minors", zh:["拟定的初期开放政策为 18 周岁及以上。未成年人请勿注册或提交个人信息；如果发现不符合年龄条件的账户，将依合法程序核实和采取措施。", "如果未来面向未成年人，需先依据地区法律建立年龄保障、监护人机制、适龄隐私设置与专门的儿童个人信息规则。中国大陆不满 14 周岁未成年人的个人信息受特别保护。"], en:["The proposed initial service is for people aged 18 and older. Minors should not register or submit personal information; suspected underage accounts will require a lawful verification and response process.", "Before admitting minors, Starflow must implement applicable age assurance, parent/guardian mechanisms, age-appropriate defaults and dedicated children’s notices. Data on children under 14 has special protection in mainland China."]},
  {id:"section-10", zhTitle:"敏感信息和特殊类别", enTitle:"Sensitive data and special categories", zh:["请不要公开发布健康、宗教、精确位置、证件、生物识别等敏感资料。如果产品功能必须处理特殊类别信息，须另行确定合法依据、必要性及额外保护措施。", "其他用户自愿发布的敏感内容，也可能造成超出网站控制范围的传播风险。"], en:["Avoid publicly posting health, religious, precise location, identity-document, biometric or other sensitive details. Processing of special categories must have an appropriate lawful basis, necessity assessment and additional safeguards.", "Even information voluntarily posted may spread beyond the service’s control."]},
  {id:"section-11", zhTitle:"Cookies、本地存储及会话", enTitle:"Cookies, local storage and sessions", zh:["为登录会话、安全和网站功能，身份服务可能使用必要 Cookie 或类似储存机制；网站当前还使用本地存储保存界面语言偏好。", "若以后使用非必要分析、广告追踪或第三方跟踪技术，应在适用地区先提供可行的同意或拒绝选择及 Cookie 说明。当前不能宣称已有完整 Cookie 管理面板。"], en:["Authentication and security may use necessary cookies or similar storage. The current interface also uses local storage to remember language preferences.", "Non-essential analytics, advertising or third-party tracking must not be enabled without the required notices and choices. A complete consent-management panel is not currently claimed."]},
  {id:"section-12", zhTitle:"保留与删除", enTitle:"Retention and deletion", zh:["账号信息及其公开内容通常在提供服务所必要的期间内保留。安全日志、举报记录及备份可能因安全、争议处理或法律要求而保留不同期限。", "保留期限取决于数据类型、用途、法律保存要求和安全需要。现有网站尚不提供一键删除所有账户数据、完整导出或即时清理备份的承诺。", "依法需要删除的数据应当依适用规定办理；删除公开内容也不一定能删除其他用户已自行保存的截图或副本。"], en:["Account data and public content are generally kept while necessary to provide the service. Security logs, reports and backups may have different retention periods for security, disputes and legal obligations.", "Retention depends on the data category, purpose, legal retention rules and security needs. The website does not currently promise one-click removal of all account data, full export or immediate erasure of backups.", "Deletion required by applicable law must be handled accordingly. Removing public content may not erase copies saved independently by other users."]},
  {id:"section-13", zhTitle:"用户权利", enTitle:"Your privacy rights", zh:["根据所在地法律，您可能有权访问、更正、复制、删除个人信息，限制或反对某些处理，获取可携带的数据副本，以及在适用时撤回同意。", "星流已有部分资料设置及动态管理功能，但专门的个人信息权利申请、验证身份、完整导出与注销功能尚未全部上线。您仍可依法向相关主管机关提出投诉。"], en:["Depending on your jurisdiction, you may have rights to access, correct, copy or delete personal data; restrict or object to certain processing; obtain portability; and withdraw consent where applicable.", "Starflow offers some profile and post management functions, but a dedicated rights-request, identity-verification, comprehensive export and account-closure workflow is not fully available yet. You may complain to the competent authority where permitted by law."]},
  {id:"section-14", zhTitle:"信息安全与事件处理", enTitle:"Security and incidents", zh:["计划采用访问权限控制、传输加密、密钥保护及操作监测等措施，但任何联网服务都无法承诺绝对安全。上线前需要独立检查数据库行级权限、存储访问、管理员授权和基础设施配置。", "发生法律规定需要通知的数据泄露时，运营者应按实际适用法律向相关人员和监管机关报告。"], en:["Access controls, transport encryption, credential protection and monitoring are intended safeguards, but no online service is perfectly secure. RLS, storage permissions, administrator access and infrastructure must be independently reviewed before launch.", "When an incident meets legal notification thresholds, the operator must notify affected individuals and regulators as required by applicable law."]},
  {id:"section-15", zhTitle:"政策更新", enTitle:"Policy updates", zh:["星流会根据产品变化、安全要求或法律义务更新本政策。依法需要告知或取得同意的重大变更，将通过适当方式处理。", "服务品牌：星流 Starflow · WEIZAI。本版更新日期：2026 年 10 月 9 日。"], en:["Starflow may revise this Policy as products, security requirements and legal duties evolve. We will provide notice or obtain consent for material changes where required by law.", "Service brand: Starflow · WEIZAI. Last updated: 9 October 2026."]},
];
export default function LegalPage(){
  const {lang}=useLanguage();
  const en=lang==='en';
  return <main className="document sf-legal-page" style={{maxWidth:920, color:'#192c31'}}>
    <div className="sf-legal-top" style={{marginBottom:20}}><Link href="/">← 星流 Starflow</Link><LanguageSwitch/></div>
    <nav aria-label={en?'Legal documents':'法律文件'} style={{display:'flex',flexWrap:'wrap',gap:10,margin:'20px 0 35px'}}>
      {navigation.map(item=><Link key={item.slug} href={'/'+item.slug} aria-current={item.slug==="privacy"?'page':undefined} style={{padding:'9px 14px',borderRadius:999,border:'1px solid #dce4e4',background:item.slug==="privacy"?'#e6f4f1':'white',fontSize:13}}>{en?item.en:item.zh}</Link>)}
    </nav>
    <p style={{fontSize:12,letterSpacing:'.08em',color:'#657279',marginBottom:10}}>{en?'STARFLOW · POLICY CENTER':'星流 STARFLOW · 政策中心'}</p>
    <h1>{en?"Privacy Policy":"隐私政策"}</h1>
    <p style={{fontSize:16,lineHeight:1.9}}>{en?"This Policy explains how Starflow handles account, public content, usage and security data. Features are described according to their actual availability.":"本政策解释星流如何处理账号、公开内容、使用记录和服务安全信息。它适用于星流面向全球用户的计划服务，并不是对尚未启用的功能作出保证。"}</p>
    <nav aria-label={en?'Contents':'目录'} style={{padding:'18px 20px',background:'#f1f6f5',borderRadius:14,marginBottom:32}}>
      <strong>{en?'Contents':'目录'}</strong>
      <ol style={{columns:'2 220px',columnGap:30,paddingLeft:22,fontSize:13,lineHeight:2}}>
        {sections.map(s=><li key={s.id} style={{breakInside:'avoid'}}><a href={'#'+s.id}>{en?s.enTitle:s.zhTitle}</a></li>)}
      </ol>
    </nav>
    <article>{sections.map((s,i)=><section id={s.id} key={s.id} style={{scrollMarginTop:20,borderBottom:'1px solid #e4ebea',padding:'8px 0 18px'}}>
      <h2 style={{fontSize:21,lineHeight:1.45,margin:'16px 0'}}>{String(i+1).padStart(2,'0')}. {en?s.enTitle:s.zhTitle}</h2>
      {(en?s.en:s.zh).map((p,j)=><p key={j} style={{lineHeight:1.95,margin:'12px 0',overflowWrap:'anywhere'}}>{p}</p>)}
    </section>)}</article>
    <footer style={{padding:'35px 0',fontSize:13,color:'#67757b'}}>
      <p>{en?'Related policies':'相关政策'}：{navigation.filter(n=>n.slug!=="privacy").map((n,i)=><span key={n.slug}>{i>0?' · ':''}<Link href={'/'+n.slug}>{en?n.en:n.zh}</Link></span>)}</p>
      <p>© 2026 Starflow · WEIZAI</p>
    </footer>
  </main>;
}
