export type Lang = 'zh' | 'en';
export const messages = {
  zh: {
    home:'首页', explore:'探索', notifications:'通知', bookmarks:'书签', settings:'设置', profile:'个人主页', admin:'管理中心',
    newPost:'发布动态', post:'发布', reply:'回复', yourWorld:'分享你的世界', forYou:'为你推荐', following:'正在关注', compose:'此刻，你在想什么？', replyPlaceholder:'写下你的回复…', photo:'添加图片', shareMoment:'文字与图片，分享真实瞬间',
    comments:'评论', repost:'转发', undoRepost:'取消转发', like:'点赞', unlike:'取消点赞', saveBookmark:'收藏', undoBookmark:'取消收藏', report:'举报动态', deletePost:'删除动态', removePhoto:'移除图片',
    exploreSub:'发现正在发生的新鲜事', search:'搜索动态或用户', people:'相关用户', notificationSub:'有人与你互动时，会显示在这里', allRead:'全部标记已读', likedYour:'赞了你的动态', repliedYou:'回复了你', followedYou:'开始关注你', repostedYou:'转发了你的动态', interacted:'与你互动了',
    settingsTitle:'账号与偏好', settingsIntro:'在一个地方管理你的账号信息与安全设置。', profileEdit:'编辑个人资料', name:'显示昵称', handle:'用户名（3–24 位英文/数字/下划线）', bio:'个人简介', save:'保存资料', security:'账号安全', securityDesc:'邮箱验证和密码重置由 Supabase Auth 处理。', resetMail:'发送密码重置邮件', logout:'退出登录', language:'语言 / Language',
    profileMissing:'用户资料', edit:'编辑资料', follow:'关注', unfollow:'已关注', missingBio:'这个人还没有填写简介。', joined:'加入 Starflow', posts:'动态', thread:'动态详情', discuss:'加入讨论', bookmarksTitle:'我的书签', bookmarksIntro:'保存值得再次阅读的内容',
    loading:'加载中…', emptyNotifications:'暂时没有新通知', emptyBook:'还没有收藏', emptyPost:'没有找到这条动态', emptyFollowing:'关注一些有趣的人吧', emptyFeed:'这里暂时还没有动态', emptyHint:'去发布第一条内容，开启新的交流。', discoverCommunity:'探索社区 →',
    rightHeadline:'正在发生', rightTitle:'欢迎来到 Starflow', rightDesc:'与感兴趣的人连接，分享此刻的想法。一个更专注于真实表达的社区。', exploreLink:'去探索 →', rules:'社区原则', ruleOne:'尊重不同观点', ruleTwo:'保护自己与他人的隐私', ruleThree:'发现违规内容，及时举报', terms:'服务条款', privacy:'隐私政策', independent:'独立社交社区 · 非 X 官方产品',
    signup:'加入 Starflow', login:'欢迎回来', forgot:'重置密码', signupDesc:'分享想法，发现志同道合的人。', loginDesc:'继续探索属于你的世界。', forgotDesc:'输入注册邮箱，我们将发送重置链接。', continueGoogle:'使用 Google 继续', orEmail:'或使用电子邮件', nickname:'你的昵称', nicknamePlace:'希望别人怎么称呼你', email:'电子邮件', password:'密码', passwordHint:'至少 12 位字符', inputPassword:'输入你的密码', create:'创建账号', loginButton:'登录 Starflow', sendReset:'发送重置邮件', processing:'处理中…', haveAccount:'已有账号？', newAccount:'还没有账号？', signIn:'立即登录', signUp:'免费注册', forgotLink:'忘记密码？', rememberPassword:'想起密码了？', backLogin:'返回登录', showPassword:'显示密码', hidePassword:'隐藏密码',
    heroLineOne:'你关心的世界，', heroLineTwo:'此刻正在发生。', heroSub:'发现有趣的人，分享真实的想法。让每一次连接，都值得期待。', heroBadge:'连接下一种可能', heroSpot:'现在，就从一句话开始', heroSpotSub:'发布 · 关注 · 对话', heroOne:'开放交流', heroTwo:'更注重隐私', heroThree:'实时连接', captchaNotReady:'尚未启用人机验证。正式开放注册前请配置 Cloudflare Turnstile。',
    configNeeded:'此项目尚未连接你的 Supabase 后端。配置环境变量后才能真实注册登录。', legalLead:'继续即表示你同意', and:'和', legalTail:'。Starflow 为独立平台。', authFooter:'为真实交流而构建 · Starflow © 2026',
    noKeys:'请先配置 Supabase 项目密钥，见 README.md。', noCaptcha:'请先配置并在 Supabase 控制台启用 Cloudflare Turnstile。', finishCaptcha:'请先完成人机验证。', pwdMinimum:'注册密码至少需要 12 位字符。', nicknameMinimum:'请输入 1–60 字的昵称。', signupConfirm:'请前往邮箱完成验证；首次登录后会尝试发送欢迎邮件。', signupDone:'注册成功，正在进入…', resetConfirm:'如该邮箱存在账号，将收到密码重置邮件，请检查收件箱。', authFailure:'操作失败，请重试。', googleFailure:'Google 登录失败。', googleNotReady:'（待配置）', authNotReady:'请先完成 Supabase 配置。',
    deletedConfirm:'确定永久删除这条动态及其回复吗？', reportReason:'请描述举报原因，例如骚扰、诈骗或垃圾信息（至少 5 字）：', reportMin:'举报原因至少需要 5 个字。', profileSaved:'个人资料已保存', posted:'发布成功', posting:'发布中…', onlyImage:'仅支持 JPG/PNG/WebP/GIF，最大 5 MB。', mustPost:'请写点内容或添加图片。', postLimit:'动态最多 280 字。', resetSent:'已请求密码重置邮件，请查看邮箱。', close:'关闭',
  },
  en: {
    home:'Home', explore:'Explore', notifications:'Notifications', bookmarks:'Bookmarks', settings:'Settings', profile:'Profile', admin:'Admin studio',
    newPost:'Create a post', post:'Post', reply:'Reply', yourWorld:'A place for every perspective', forYou:'For you', following:'Following', compose:'What’s happening?', replyPlaceholder:'Write a reply…', photo:'Add photo', shareMoment:'Share a thought or a photo',
    comments:'Replies', repost:'Repost', undoRepost:'Undo repost', like:'Like', unlike:'Unlike', saveBookmark:'Save post', undoBookmark:'Remove bookmark', report:'Report post', deletePost:'Delete post', removePhoto:'Remove photo',
    exploreSub:'Discover what’s happening', search:'Search posts or people', people:'People', notificationSub:'Your interactions appear here', allRead:'Mark all as read', likedYour:'liked your post', repliedYou:'replied to you', followedYou:'started following you', repostedYou:'reposted your post', interacted:'interacted with you',
    settingsTitle:'Account & preferences', settingsIntro:'Manage your profile and security preferences in one place.', profileEdit:'Edit profile', name:'Display name', handle:'Username (3–24 lowercase letters, numbers, underscores)', bio:'Bio', save:'Save changes', security:'Account security', securityDesc:'Email verification and password recovery are handled by Supabase Auth.', resetMail:'Send password reset email', logout:'Log out', language:'Language / 语言',
    profileMissing:'Profile', edit:'Edit profile', follow:'Follow', unfollow:'Following', missingBio:'No bio yet.', joined:'Joined Starflow', posts:'Posts', thread:'Post details', discuss:'Join the conversation', bookmarksTitle:'Your bookmarks', bookmarksIntro:'Keep the good stuff close',
    loading:'Loading…', emptyNotifications:'No new notifications', emptyBook:'No bookmarks yet', emptyPost:'This post could not be found', emptyFollowing:'Find some interesting people to follow', emptyFeed:'Nothing here yet', emptyHint:'Share your first thought and join the conversation.', discoverCommunity:'Explore the community →',
    rightHeadline:'What’s happening', rightTitle:'Welcome to Starflow', rightDesc:'Connect with people who inspire you and share your thoughts in a place built for real conversation.', exploreLink:'Explore →', rules:'Community guidelines', ruleOne:'Respect different points of view', ruleTwo:'Protect everyone’s privacy', ruleThree:'Report abusive content', terms:'Terms of service', privacy:'Privacy policy', independent:'Independent social community · Not affiliated with X',
    signup:'Join Starflow', login:'Welcome back', forgot:'Reset your password', signupDesc:'Share your story. Find your people.', loginDesc:'Pick up where you left off.', forgotDesc:'Enter your email to receive a reset link.', continueGoogle:'Continue with Google', orEmail:'or continue with email', nickname:'Display name', nicknamePlace:'What should people call you?', email:'Email address', password:'Password', passwordHint:'At least 12 characters', inputPassword:'Enter your password', create:'Create account', loginButton:'Log in', sendReset:'Send reset link', processing:'Please wait…', haveAccount:'Already have an account?', newAccount:'New to Starflow?', signIn:'Log in', signUp:'Sign up', forgotLink:'Forgot password?', rememberPassword:'Remembered it?', backLogin:'Back to login', showPassword:'Show password', hidePassword:'Hide password',
    heroLineOne:'Your world.', heroLineTwo:'Your conversation.', heroSub:'Find people who inspire you. Share thoughts that matter. Make every connection count.', heroBadge:'A new kind of connection', heroSpot:'Your next story starts here', heroSpotSub:'Share · Follow · Connect', heroOne:'Open conversations', heroTwo:'Privacy matters', heroThree:'Instant connection', captchaNotReady:'CAPTCHA is not enabled. Configure Cloudflare Turnstile before accepting registrations.',
    configNeeded:'This project is not connected to Supabase yet. Configure environment variables to enable real sign-in.', legalLead:'By continuing you agree to our', and:'and', legalTail:'. Starflow is an independent platform.', authFooter:'Made for meaningful connection · Starflow © 2026',
    noKeys:'Configure Supabase project credentials first; see README.md.', noCaptcha:'Enable Cloudflare Turnstile in your site and Supabase dashboard.', finishCaptcha:'Complete the human verification first.', pwdMinimum:'Passwords must have at least 12 characters.', nicknameMinimum:'Enter a display name between 1 and 60 characters.', signupConfirm:'Please verify your email. A welcome email will be attempted after your first verified sign-in.', signupDone:'Account created. Signing you in…', resetConfirm:'If this email exists, you will receive a reset link. Please check your inbox.', authFailure:'Something went wrong. Try again.', googleFailure:'Google sign-in failed.', googleNotReady:'(setup required)', authNotReady:'Configure Supabase first.',
    deletedConfirm:'Permanently delete this post and its replies?', reportReason:'Why are you reporting this post? (at least 5 characters)', reportMin:'Please enter at least 5 characters.', profileSaved:'Profile saved', posted:'Post published', posting:'Posting…', onlyImage:'Only JPG/PNG/WebP/GIF files up to 5 MB are allowed.', mustPost:'Write something or add a photo.', postLimit:'Posts have a maximum of 280 characters.', resetSent:'Password reset email requested. Check your inbox.', close:'Close',
  }
} as const;
export type TranslationKey = keyof typeof messages.zh;
export function translate(lang:Lang, key:TranslationKey):string{return messages[lang][key]??messages.zh[key]}
