
name: Starflow Code Check

on:
  push:
    branches:
      - main
      - starflow-2-messaging
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starflow-social

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
          

      - name: Install dependencies
        run: npm install

      - name: Check TypeScript
        run: npm run lint

      - name: Build website
        run: npm run build
